language: python

python: 3.6

env:
  - AWS_ACCESS_KEY_ID=1234 AWS_DEFAULT_REGION=us-west-1 AWS_SECRET_ACCESS_KEY=shhh

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

script: pipenv run pytest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
