language: python

python: 3.6

install:
    -  pip install pipenv
    -  pipenv install --dev -skip-lock

script: pipenv run pytest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
